// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: v1/request_vote.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestVoteService_RequestVote_FullMethodName = "/v1.RequestVoteService/RequestVote"
)

// RequestVoteServiceClient is the client API for RequestVoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestVoteServiceClient interface {
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
}

type requestVoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestVoteServiceClient(cc grpc.ClientConnInterface) RequestVoteServiceClient {
	return &requestVoteServiceClient{cc}
}

func (c *requestVoteServiceClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, RequestVoteService_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestVoteServiceServer is the server API for RequestVoteService service.
// All implementations must embed UnimplementedRequestVoteServiceServer
// for forward compatibility.
type RequestVoteServiceServer interface {
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	mustEmbedUnimplementedRequestVoteServiceServer()
}

// UnimplementedRequestVoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestVoteServiceServer struct{}

func (UnimplementedRequestVoteServiceServer) RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRequestVoteServiceServer) mustEmbedUnimplementedRequestVoteServiceServer() {}
func (UnimplementedRequestVoteServiceServer) testEmbeddedByValue()                            {}

// UnsafeRequestVoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestVoteServiceServer will
// result in compilation errors.
type UnsafeRequestVoteServiceServer interface {
	mustEmbedUnimplementedRequestVoteServiceServer()
}

func RegisterRequestVoteServiceServer(s grpc.ServiceRegistrar, srv RequestVoteServiceServer) {
	// If the following call panics, it indicates UnimplementedRequestVoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestVoteService_ServiceDesc, srv)
}

func _RequestVoteService_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestVoteServiceServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestVoteService_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestVoteServiceServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestVoteService_ServiceDesc is the grpc.ServiceDesc for RequestVoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestVoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RequestVoteService",
	HandlerType: (*RequestVoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestVote",
			Handler:    _RequestVoteService_RequestVote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/request_vote.proto",
}
