// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/recovery/copy_on_write.go

package mocks

import (
	reflect "reflect"

	"github.com/tuanta7/cataraft/internal/storage/disk"
	recovery "github.com/tuanta7/cataraft/internal/storage/writer/cow"
	gomock "go.uber.org/mock/gomock"
)

type MockCopyOnWriteStore struct {
	ctrl     *gomock.Controller
	recorder *MockCopyOnWriteStoreMockRecorder
	isgomock struct{}
}

type MockCopyOnWriteStoreMockRecorder struct {
	mock *MockCopyOnWriteStore
}

func NewMockCopyOnWriteStore(ctrl *gomock.Controller) *MockCopyOnWriteStore {
	mock := &MockCopyOnWriteStore{ctrl: ctrl}
	mock.recorder = &MockCopyOnWriteStoreMockRecorder{mock}
	return mock
}

func (m *MockCopyOnWriteStore) EXPECT() *MockCopyOnWriteStoreMockRecorder {
	return m.recorder
}

func (m *MockCopyOnWriteStore) ReadPage(id disk.PageID) (*disk.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPage", id)
	ret0, _ := ret[0].(*disk.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCopyOnWriteStoreMockRecorder) ReadPage(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPage", reflect.TypeOf((*MockCopyOnWriteStore)(nil).ReadPage), id)
}

func (m *MockCopyOnWriteStore) WritePage(id disk.PageID, page *disk.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePage", id, page)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCopyOnWriteStoreMockRecorder) WritePage(id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePage", reflect.TypeOf((*MockCopyOnWriteStore)(nil).WritePage), id, page)
}

func (m *MockCopyOnWriteStore) SyncFile(fn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFile", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockCopyOnWriteStoreMockRecorder) SyncFile(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFile", reflect.TypeOf((*MockCopyOnWriteStore)(nil).SyncFile), fn)
}

func (m *MockCopyOnWriteStore) AppendFile(fn string, data []byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendFile", fn, data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCopyOnWriteStoreMockRecorder) AppendFile(fn, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFile", reflect.TypeOf((*MockCopyOnWriteStore)(nil).AppendFile), fn, data)
}

func (m *MockCopyOnWriteStore) ReadFileAt(fn string, offset int64, buf []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileAt", fn, offset, buf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCopyOnWriteStoreMockRecorder) ReadFileAt(fn, offset, buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileAt", reflect.TypeOf((*MockCopyOnWriteStore)(nil).ReadFileAt), fn, offset, buf)
}

func (m *MockCopyOnWriteStore) FileSize(fn string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize", fn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockCopyOnWriteStoreMockRecorder) FileSize(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*MockCopyOnWriteStore)(nil).FileSize), fn)
}

var _ recovery.CopyOnWriteStore = (*MockCopyOnWriteStore)(nil)
