// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/disk/copyonwrite/adapter.go
//
// Generated by this command:
//
//	mockgen -source=./internal/storage/disk/copyonwrite/adapter.go -destination=./mocks/copy_on_write_store.go -package=mock -mock_names Store=CopyOnWriteStore
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	disk "github.com/tuanta7/cataraft/internal/storage/disk"
	gomock "go.uber.org/mock/gomock"
)

// CopyOnWriteStore is a mock of Store interface.
type CopyOnWriteStore struct {
	ctrl     *gomock.Controller
	recorder *CopyOnWriteStoreMockRecorder
	isgomock struct{}
}

// CopyOnWriteStoreMockRecorder is the mock recorder for CopyOnWriteStore.
type CopyOnWriteStoreMockRecorder struct {
	mock *CopyOnWriteStore
}

// NewCopyOnWriteStore creates a new mock instance.
func NewCopyOnWriteStore(ctrl *gomock.Controller) *CopyOnWriteStore {
	mock := &CopyOnWriteStore{ctrl: ctrl}
	mock.recorder = &CopyOnWriteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *CopyOnWriteStore) EXPECT() *CopyOnWriteStoreMockRecorder {
	return m.recorder
}

// AppendFile mocks base method.
func (m *CopyOnWriteStore) AppendFile(fn string, data []byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendFile", fn, data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendFile indicates an expected call of AppendFile.
func (mr *CopyOnWriteStoreMockRecorder) AppendFile(fn, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFile", reflect.TypeOf((*CopyOnWriteStore)(nil).AppendFile), fn, data)
}

// FileSize mocks base method.
func (m *CopyOnWriteStore) FileSize(fn string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize", fn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileSize indicates an expected call of FileSize.
func (mr *CopyOnWriteStoreMockRecorder) FileSize(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*CopyOnWriteStore)(nil).FileSize), fn)
}

// ReadFileAt mocks base method.
func (m *CopyOnWriteStore) ReadFileAt(fn string, offset int64, buf []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileAt", fn, offset, buf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileAt indicates an expected call of ReadFileAt.
func (mr *CopyOnWriteStoreMockRecorder) ReadFileAt(fn, offset, buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileAt", reflect.TypeOf((*CopyOnWriteStore)(nil).ReadFileAt), fn, offset, buf)
}

// ReadPage mocks base method.
func (m *CopyOnWriteStore) ReadPage(id disk.PageID) (*disk.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPage", id)
	ret0, _ := ret[0].(*disk.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPage indicates an expected call of ReadPage.
func (mr *CopyOnWriteStoreMockRecorder) ReadPage(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPage", reflect.TypeOf((*CopyOnWriteStore)(nil).ReadPage), id)
}

// SyncFile mocks base method.
func (m *CopyOnWriteStore) SyncFile(fn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFile", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFile indicates an expected call of SyncFile.
func (mr *CopyOnWriteStoreMockRecorder) SyncFile(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFile", reflect.TypeOf((*CopyOnWriteStore)(nil).SyncFile), fn)
}

// WritePage mocks base method.
func (m *CopyOnWriteStore) WritePage(id disk.PageID, page *disk.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePage", id, page)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePage indicates an expected call of WritePage.
func (mr *CopyOnWriteStoreMockRecorder) WritePage(id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePage", reflect.TypeOf((*CopyOnWriteStore)(nil).WritePage), id, page)
}
