// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/buffer/buffer.go

package mocks

import (
	reflect "reflect"

	buffer "github.com/tuanta7/cataraft/internal/storage/buffer"
	disk "github.com/tuanta7/cataraft/internal/storage/disk"
	gomock "go.uber.org/mock/gomock"
)

type MockDirtyPageWriter struct {
	ctrl     *gomock.Controller
	recorder *MockDirtyPageWriterMockRecorder
	isgomock struct{}
}

type MockDirtyPageWriterMockRecorder struct {
	mock *MockDirtyPageWriter
}

func NewMockDirtyPageWriter(ctrl *gomock.Controller) *MockDirtyPageWriter {
	mock := &MockDirtyPageWriter{ctrl: ctrl}
	mock.recorder = &MockDirtyPageWriterMockRecorder{mock}
	return mock
}

func (m *MockDirtyPageWriter) EXPECT() *MockDirtyPageWriterMockRecorder {
	return m.recorder
}

func (m *MockDirtyPageWriter) StagePage(id disk.PageID, page *disk.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StagePage", id, page)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDirtyPageWriterMockRecorder) StagePage(id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StagePage", reflect.TypeOf((*MockDirtyPageWriter)(nil).StagePage), id, page)
}

func (m *MockDirtyPageWriter) FlushPage(id disk.PageID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushPage", id)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDirtyPageWriterMockRecorder) FlushPage(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushPage", reflect.TypeOf((*MockDirtyPageWriter)(nil).FlushPage), id)
}

var _ buffer.SafeWriter = (*MockDirtyPageWriter)(nil)
