// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/recovery/double_write.go

package mocks

import (
	reflect "reflect"

	"github.com/tuanta7/cataraft/internal/storage/disk"
	recovery "github.com/tuanta7/cataraft/internal/storage/writer/dwb"
	gomock "go.uber.org/mock/gomock"
)

type MockDoubleWriteStore struct {
	ctrl     *gomock.Controller
	recorder *MockDoubleWriteStoreMockRecorder
	isgomock struct{}
}

type MockDoubleWriteStoreMockRecorder struct {
	mock *MockDoubleWriteStore
}

func NewMockDoubleWriteStore(ctrl *gomock.Controller) *MockDoubleWriteStore {
	mock := &MockDoubleWriteStore{ctrl: ctrl}
	mock.recorder = &MockDoubleWriteStoreMockRecorder{mock}
	return mock
}

func (m *MockDoubleWriteStore) EXPECT() *MockDoubleWriteStoreMockRecorder {
	return m.recorder
}

func (m *MockDoubleWriteStore) ReadPage(id disk.PageID) (*disk.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPage", id)
	ret0, _ := ret[0].(*disk.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDoubleWriteStoreMockRecorder) ReadPage(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPage", reflect.TypeOf((*MockDoubleWriteStore)(nil).ReadPage), id)
}

func (m *MockDoubleWriteStore) WritePage(id disk.PageID, page *disk.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePage", id, page)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDoubleWriteStoreMockRecorder) WritePage(id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePage", reflect.TypeOf((*MockDoubleWriteStore)(nil).WritePage), id, page)
}

func (m *MockDoubleWriteStore) SyncFile(fn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFile", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockDoubleWriteStoreMockRecorder) SyncFile(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFile", reflect.TypeOf((*MockDoubleWriteStore)(nil).SyncFile), fn)
}

var _ recovery.DoubleWriteStore = (*MockDoubleWriteStore)(nil)
