// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/recovery/log.go

package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	recovery "github.com/tuanta7/cataraft/internal/storage/recovery"
)

// MockLogStore is a mock of LogStore interface.
type MockLogStore struct {
	ctrl     *gomock.Controller
	recorder *MockLogStoreMockRecorder
	isgomock struct{}
}

// MockLogStoreMockRecorder is the mock recorder for MockLogStore.
type MockLogStoreMockRecorder struct {
	mock *MockLogStore
}

// NewMockLogStore creates a new mock instance.
func NewMockLogStore(ctrl *gomock.Controller) *MockLogStore {
	mock := &MockLogStore{ctrl: ctrl}
	mock.recorder = &MockLogStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogStore) EXPECT() *MockLogStoreMockRecorder {
	return m.recorder
}

// AppendFile mocks base method.
func (m *MockLogStore) AppendFile(fn string, data []byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendFile", fn, data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendFile indicates an expected call of AppendFile.
func (mr *MockLogStoreMockRecorder) AppendFile(fn, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFile", reflect.TypeOf((*MockLogStore)(nil).AppendFile), fn, data)
}

// ReadFileAt mocks base method.
func (m *MockLogStore) ReadFileAt(fn string, offset int64, buf []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileAt", fn, offset, buf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileAt indicates an expected call of ReadFileAt.
func (mr *MockLogStoreMockRecorder) ReadFileAt(fn, offset, buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileAt", reflect.TypeOf((*MockLogStore)(nil).ReadFileAt), fn, offset, buf)
}

// FileSize mocks base method.
func (m *MockLogStore) FileSize(fn string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize", fn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileSize indicates an expected call of FileSize.
func (mr *MockLogStoreMockRecorder) FileSize(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*MockLogStore)(nil).FileSize), fn)
}

// SyncFile mocks base method.
func (m *MockLogStore) SyncFile(fn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFile", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFile indicates an expected call of SyncFile.
func (mr *MockLogStoreMockRecorder) SyncFile(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFile", reflect.TypeOf((*MockLogStore)(nil).SyncFile), fn)
}

var _ recovery.LogStore = (*MockLogStore)(nil)
