// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/buffer/buffer.go

package mocks

import (
	reflect "reflect"

	buffer "github.com/tuanta7/cataraft/internal/storage/buffer"
	disk "github.com/tuanta7/cataraft/internal/storage/disk"
	gomock "go.uber.org/mock/gomock"
)

// MockPageStore is a mock of PageStore interface.
type MockPageStore struct {
	ctrl     *gomock.Controller
	recorder *MockPageStoreMockRecorder
	isgomock struct{}
}

// MockPageStoreMockRecorder is the mock recorder for MockPageStore.
type MockPageStoreMockRecorder struct {
	mock *MockPageStore
}

// NewMockPageStore creates a new mock instance.
func NewMockPageStore(ctrl *gomock.Controller) *MockPageStore {
	mock := &MockPageStore{ctrl: ctrl}
	mock.recorder = &MockPageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPageStore) EXPECT() *MockPageStoreMockRecorder {
	return m.recorder
}

// ReadPage mocks base method.
func (m *MockPageStore) ReadPage(id disk.PageID) (*disk.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPage", id)
	ret0, _ := ret[0].(*disk.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPage indicates an expected call of ReadPage.
func (mr *MockPageStoreMockRecorder) ReadPage(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPage", reflect.TypeOf((*MockPageStore)(nil).ReadPage), id)
}

// WritePage mocks base method.
func (m *MockPageStore) WritePage(id disk.PageID, page *disk.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePage", id, page)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePage indicates an expected call of WritePage.
func (mr *MockPageStoreMockRecorder) WritePage(id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePage", reflect.TypeOf((*MockPageStore)(nil).WritePage), id, page)
}

var _ buffer.PageStore = (*MockPageStore)(nil)
