// Code generated by MockGen. DO NOT EDIT.
// Source: internal/storage/recovery/double_write.go

package mocks

import (
	reflect "reflect"

	recovery "github.com/tuanta7/cataraft/internal/storage/writer/dwb"
	gomock "go.uber.org/mock/gomock"
)

type MockWALFlusher struct {
	ctrl     *gomock.Controller
	recorder *MockWALFlusherMockRecorder
	isgomock struct{}
}

type MockWALFlusherMockRecorder struct {
	mock *MockWALFlusher
}

func NewMockWALFlusher(ctrl *gomock.Controller) *MockWALFlusher {
	mock := &MockWALFlusher{ctrl: ctrl}
	mock.recorder = &MockWALFlusherMockRecorder{mock}
	return mock
}

func (m *MockWALFlusher) EXPECT() *MockWALFlusherMockRecorder {
	return m.recorder
}

func (m *MockWALFlusher) FlushedLSN() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushedLSN")
	ret0, _ := ret[0].(uint64)
	return ret0
}

func (mr *MockWALFlusherMockRecorder) FlushedLSN() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushedLSN", reflect.TypeOf((*MockWALFlusher)(nil).FlushedLSN))
}

func (m *MockWALFlusher) FlushThrough(lsn uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FlushThrough", lsn)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockWALFlusherMockRecorder) FlushThrough(lsn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushThrough", reflect.TypeOf((*MockWALFlusher)(nil).FlushThrough), lsn)
}

var _ recovery.WALFlusher = (*MockWALFlusher)(nil)
