// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/storage/writer/cow/buffer.go
//
// Generated by this command:
//
//	mockgen -source=./internal/storage/writer/cow/buffer.go -destination=./mocks/cow/copy_on_write.go -package=mockcow
//

// Package mockcow is a generated GoMock package.
package mockcow

import (
	reflect "reflect"

	disk "github.com/tuanta7/cataraft/internal/storage/disk"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AppendFile mocks base method.
func (m *MockStore) AppendFile(fn string, data []byte) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendFile", fn, data)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendFile indicates an expected call of AppendFile.
func (mr *MockStoreMockRecorder) AppendFile(fn, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendFile", reflect.TypeOf((*MockStore)(nil).AppendFile), fn, data)
}

// FileSize mocks base method.
func (m *MockStore) FileSize(fn string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize", fn)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileSize indicates an expected call of FileSize.
func (mr *MockStoreMockRecorder) FileSize(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*MockStore)(nil).FileSize), fn)
}

// ReadFileAt mocks base method.
func (m *MockStore) ReadFileAt(fn string, offset int64, buf []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileAt", fn, offset, buf)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileAt indicates an expected call of ReadFileAt.
func (mr *MockStoreMockRecorder) ReadFileAt(fn, offset, buf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileAt", reflect.TypeOf((*MockStore)(nil).ReadFileAt), fn, offset, buf)
}

// ReadPage mocks base method.
func (m *MockStore) ReadPage(id disk.PageID) (*disk.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPage", id)
	ret0, _ := ret[0].(*disk.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPage indicates an expected call of ReadPage.
func (mr *MockStoreMockRecorder) ReadPage(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPage", reflect.TypeOf((*MockStore)(nil).ReadPage), id)
}

// SyncFile mocks base method.
func (m *MockStore) SyncFile(fn string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFile", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFile indicates an expected call of SyncFile.
func (mr *MockStoreMockRecorder) SyncFile(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFile", reflect.TypeOf((*MockStore)(nil).SyncFile), fn)
}

// WritePage mocks base method.
func (m *MockStore) WritePage(id disk.PageID, page *disk.Page) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePage", id, page)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePage indicates an expected call of WritePage.
func (mr *MockStoreMockRecorder) WritePage(id, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePage", reflect.TypeOf((*MockStore)(nil).WritePage), id, page)
}
